### ISSUE TITLE
Disambiguate "reference"

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/wg-reference-types#41]
Using "reference" in this working group and the resulting proposals will be confusing with the existing term for a "reference" which is a name used to pull images from a registry ([see distribution/distribution](https://github.com/distribution/distribution/blob/a7fc49b0679dcd25d2e24524a965dc39e4128a3c/reference/reference.go)). We should avoid using that name where possible. Is "referrers" and "refer" better?

**Comment by AkihiroSuda** [comment]
> Is "referrers" and "refer" better?

Still very confusing to me.
What about renaming wg-reference-types to something like wg-artifact-linkage or wg-artifact-relations ?

**Comment by vsoch** [comment]
Wanted to jump in and commnt here! I don't know what it is about "referrers" but my brain does a twist around it and I either develop a sudden lisp or want to say "furries" because of the double R. I agree "reference" is confusing, and really I'm open for just about anything else! :laughing: Some ideas:

- links: (but doesn't imply one way)
- refers: would work for me - it's sort of an alias for "refers to" and references the child pointing to the parent?
- refs: is this not distinct enough from the full "references" ? We could adopt the other terminology to use this less (and use hash/digest, etc).
- edge: (more graph, but again doesn't imply one way)
- pointers: (direction can be one way, but are people too traumatized by C/C++ for this to be an option? I might be...)
- describes: this might be too close to "description" which is all over the place...
- needs/deps: to scope this into package management territory, technically a signature/SBOM may depend on an artifact, or an artifact may need a signature. We would have to define a clear definition and direction.
- targets: a source targets a target, not sure if that s too generic.

I'll post again if I can think of anything good.

**Comment by sudo-bmitch** [comment]
We're using "refers" now in the manifest so say this manifest refers to another (an artifact refers to an image). The API was looking for everything that has a refers entry pointing to the target manifest, so we're saying for a given image, what are all the referrers to this manifest. I'm definitely not picky here, if we want to change that to "refers" in both places, that's easy enough. The risk is confusing things that refer to this manifest with things this manifest refers to, but I don't think we'd ever add a registry API for the latter, that's just content of the manifest.

The other name that comes to mind is:

- extends: this has added connotations I think we should avoid

**Comment by vsoch** [comment]
I did still see a few mentions of "referrers" in the draft so if "refers" is now being used (which is much better!) it might be good to update the wording there too.

**Comment by sudo-bmitch** [comment]
@vsoch yup, it says referrers all over it, mostly for the API which does use that term. It gets back to that directionality, referrers looks for incoming links, refers defines an outgoing link. But I'm horrible with words and happy to use better ones, hence the reason we have all gathered here today. 😂

**Comment by jdolitsky** [comment]
Closing as PRs are open in upstream repos
