### ISSUE TITLE
Updates to Proposal E

### ISSUE THREAD

**Issue by lachie83** [opencontainers/wg-reference-types#42]
As per the WG discussion today  (5/3/2022) there was agreement on the call to start to finalize any changes to prepare [Proposal E](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md) for presentation to the OCI as the output "proposal" of this WG. Here are the points that we agreed on that need to happen in the meeting (please let me know if we need any changes):

- [x]   Update new manifest with example
   * Confirm if the new manifest could be the same as [Proposal A](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_A.md) rather than the few changes (Just need an explanation on why because they may be fine) 
- [x]  Remove filtering from Proposal E completely
- [x]  Use distribution extensions for references HTTP API endpoint so that no changes to distribution-spec are required
- [x]  Add some context around upgrade path to new manifest for registry providers
- [ ]  Making the upgrade path more clear regarding the end goal (added 6/28/22)

The following actions were also captured along side Proposal E to support the change:
* Clarify verbiage about specific and general concerns for changes to the image-spec

Description changelog
- Converted bulleted list to task list (lachie83)
- Checked task 2,3,4 (lachie83)
- Added task 5 upgrade path more clear to task list (lachie83)

This issue can be used to link all related PRs that action the list above.

**Comment by imjasonh** [comment]
> * Confirm if the new manifest could be the same as [Proposal A](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_A.md) rather than the few changes (Just need an explanation on why because they may be fine)

Can you list the changes you're interested in discussing? Based on a quick reading, I think it's:

- `artifactType` is dropped
- `subject` -> `reference`
- `/v2/<name>/_oci/artifacts/referrers?digest=<digest>` -> `/v2/<name>/references/<digest>`
  - i.e., an OCI extension vs. a new "official" endpoint
- referrers API returning `{"references": [<descriptors>]}` -> an index of descriptors

Any other big diffs I missed?

> Remove filtering from Proposal E completely

+1, and I think generally +1s from around the call

**Comment by sudo-bmitch** [comment]
If we remove filtering, we'll also need to adjust the responses to the requirements. Or will filtering still be possible to implement later? If the latter, we may want to specify what features the future filtering capabilities will provide.

**Comment by sudo-bmitch** [comment]
Are distribution-spec extensions required for every change going forward? My understanding of the value of the extensions was they gave registry operators a way to add features that wouldn't conflict with other registry operators or with future OCI additions. It's probably worth raising that question with OCI.

**Comment by sudo-bmitch** [comment]
> This issue can be used to link all related PRs that action the list above.

Should we break this into multiple issues? A PR for one concern that says it fixes this issue would close it for all of them.

**Comment by sajayantony** [comment]
@imjasonh I can try to describe a challenge we had when dropping filtering all together and that is why Prop A was leaning towards a minimum viable experience with filtering on just artifact type. Say we stored 2 types of things with an image, we end up having to iterate overall references to get to a type that might not be frequently updated. 
For a more concrete example if we have a scan being attached on a daily basis, then to get to a signature which might be updated only once in while, we might have to iterate over the scans first. 

Honestly the artifactType filtering was a compromise without having to build full blown rich query over annotations. I agree that annotations filtering might be the right experience but just costly to do without some kind of indexed store. 

@sudo-bmitch linking the issue here since the outcome of https://github.com/opencontainers/distribution-spec/issues/324 discussion can help define if we propose under `v2/{repo}/references/{digest}` or `/v2/{repo}/_oci...,`  
I don't have a strong opinion. We might just have a low friction path to add an OCI extension and just add another section to list of extension. Maybe @mikebrow can weigh in on this. 

For example we add a `referrers` or `references` module similar to - https://github.com/opencontainers/distribution-spec/blob/main/extensions/_oci.md#module-discover

**Comment by sajayantony** [comment]
From today's 2 points that might be important to discuss for the final specification are - 

1. Can we remove the hash so that tag listing is not required for getting the referrers when using the fallback.  - @sajayantony 
    - would this introduce race conditions and become F @sudo-bmitch 
3. Should we consider moving up non-tool or artifact specific field into the manifest. 
    - This might mean we move up `artifactType` into the manifest instead of using an annotation.  @michaelb990

**Comment by sudo-bmitch** [comment]
Summarizing some of the concerns with making the tag names predictable (removing the extra hash): this creates the race condition seen with Proposal F, and would require clients to push an index to the tag instead of their artifact. I'm open to having the community push for that direction, but I want to be sure we understand the extra workload pushed on the client, along with a desire to support ETags when doing that.

The other question was for adding more 1st class data into the artifact manifest, and less reliance on annotations. When I was working through the backward compatibility solution with image-spec, I was working with what we had there as best I could, so I was leaning on annotation for that. Since clients should have all that logic in annotations to support existing registries, it felt like more work to add another way to store the same data in an artifact manifest, map between the two ways to represent the same data, and sort out what to do if someone pushes those fields both ways, particularly if they weren't the same. So I was leaning towards one set of client side logic regardless of which manifest was was used. Similar to tag naming, that's not a final decision, more than happy to discuss options and follow the community's lead.

**Comment by michaelb990** [comment]
>Should we consider moving up non-tool or artifact specific field into the manifest.
This might mean we move up artifactType into the manifest instead of using an annotation. @michaelb990

+1 to this. I'd like to see `artifactType` as a top-level field in the manifest and as something that registries SHOULD support filtering on. 

I'm picturing the number of references an image will have increasing rather quickly as additional use cases come online. `artifactType` filtering will ensure that one use case that produces a lot of artifacts can't impact performance for another use case, since they'll have different `artifactType`s and registries that need to scale can provide the ability to filter out the unneeded references on the server side. This will be especially important for latency-sensitive use cases that need to retrieve a single reference without having to page through everything.

**Comment by michaelb990** [comment]
A couple more questions for discussion:
* Should we focus on only the [artifact spec](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#artifact-spec) for manifest changes, instead of adding reference support to both a new artifact spec and the existing [image spec](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#image-spec)? I see less use cases for reference support in the image manifest, so it seems like a potential way to reduce the total number of changes we need to make to achieve the goals of this working group. 
* Do we need to lift the full annotations map into the [Referrers API](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#referrers-api)? The API is supposed to be a list of descriptors to the references, not the full manifests. Returning the descriptors w/ annotations greatly increases the chances that manifests with high numbers of annotations cause issues for registries and requires registries do pretty much the same amount of work as they would just returning the manifests in their entirety since the annotations map is only bounded by the max size of a manifest.

**Comment by sudo-bmitch** [comment]
From the meeting today:

- Make sure other registry operators agree with our direction
- Draft PR for promoting artifact-type to artifact manifest, similar draft PR's can be used for other suggestions
- Document garbage collection and any other important assumptions in the requirements

**Comment by sudo-bmitch** [comment]
@michaelb990 
> +1 to this. I'd like to see `artifactType` as a top-level field in the manifest and as something that registries SHOULD support filtering on.

I've added #59 to discuss this. Adding filtering can be done later.

>     * Should we focus on only the [artifact spec](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#artifact-spec) for manifest changes, instead of adding reference support to both a new artifact spec and the existing [image spec](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#image-spec)? I see less use cases for reference support in the image manifest, so it seems like a potential way to reduce the total number of changes we need to make to achieve the goals of this working group.

Capturing the discussion in today's meeting (for anyone that missed it): I think >95% of artifacts will initially be image-spec only, for portability between registries that don't have support for the new manifest types. It's not possible to push an artifact-spec media type to a registry today (the manifest media type is processed by registries and unknown values are rejected as unknown manifest types). Best guess is we'll see this last for 5 or so years, and then only new artifacts will be pushed with the new media types and we'll still need to support all of the existing artifacts that were previously pushed with image-spec artifacts.

>     * Do we need to lift the full annotations map into the [Referrers API](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_E.md#referrers-api)? The API is supposed to be a list of descriptors to the references, not the full manifests. Returning the descriptors w/ annotations greatly increases the chances that manifests with high numbers of annotations cause issues for registries and requires registries do pretty much the same amount of work as they would just returning the manifests in their entirety since the annotations map is only bounded by the max size of a manifest.

It's a tradeoff. If we don't lift the annotations, then clients have to pull every manifest to locate the one matching their criteria. If we do lift manifests, then a bad actor could fill annotations for one or more manifests with excessive data triggering paging. My preference is to optimize for the well behaved clients and minimize the number of manifest pulls required, but I realize that's a client optimized view.

**Comment by jdolitsky** [comment]
These discussions seemed to have moved to individual votes/PRs so closing this issue for now
