### ISSUE TITLE
What are the issues with Proposal F?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/wg-reference-types#53]
Please list here any concerns you would like to discuss relating to [Proposal F](https://github.com/opencontainers/wg-reference-types/blob/main/docs/proposals/PROPOSAL_F.md)

**Comment by sudo-bmitch** [comment]
One concern is race conditions. Two systems may want to add metadata to the same image. The extended Index would have the following states:

A: original index
E: extended index
E1: E with client 1's additions
E2: E with client 2's additions

Both E1 and E2 can be pushed and the last to push wins, losing the changes from the other client. This could be solved by server side changes to support ETags, but that won't help existing registries that don't have these features. Trying to prevent it on the client side is very error prone:

- A client may miss changes pushed just before they push
- A client may not wait long enough to see their changes were overwritten
- One client may undo multiple changes made by other clients, triggering each of those clients to retry their individual changes
- A client trying to intentionally delete an index entry may fight with the clients that can't differentiate between a deletion and data loss from a race condition
- An index changed by lots of clients may result in a poor UX where one client may continue to retry multiple times

**Comment by sudo-bmitch** [comment]
The proposal has several scalability limitations.

- There are practical limits to the number of concurrent clients making changes because of race conditions mentioned above.
- An Index has a maximum manifest size we need to remain below (4MB). There is a maximum number of added entries that can be added, and a potential DoS if some entries contain a large amount of annotation data.
- Some clients have a limit on the annotation size (I'm hearing 4KB in containerd for the combination of key and value)

**Comment by sudo-bmitch** [comment]
We need some testing with runtimes to see how they handle nested Index's, and manifest entries in an Index without a platform included.

**Comment by sudo-bmitch** [comment]
It's not clear how to sign a single platform specific manifest that could exist in multiple manifests. Does there need to be a 3rd Index for just the platform specific manifest, located by a digest tag, separate from the multi-platform Index? And do clients need to query both the Index digest and the Image digest for tags listing extensions?

**Comment by sudo-bmitch** [comment]
If tags are immutable, it's not possible to update the digest tag to point to an extended image.

**Comment by sajayantony** [comment]
The OCI WG doesn't have to specify the sharding mechanisms in the specification, but it would be good to discuss and outline this in a conversation on how clients should update the index safely besides the ETAG discussion since the other proposals did not update the same entity. 

For e.g. @tonistiigi's idea about sharded index might solve grouping issues but might require 2 or more manifest puts. 

If things are being appended beyond the recommended the limit clients may have a few options to update the last item and/or move it into a nested index depending on the item they are attaching or even reorganize into multiple indexes. 

I recognize that the WG spec will not define the details but the goal of the working group is to ensure that clients can attach things like signatures/sboms/scan results  etc. So discussing this is important IMHO even if we don't write it down in the specification.

**Comment by tonistiigi** [comment]
@sudo-bmitch 

> An Index has a maximum manifest size we need to remain below (4MB). There is a maximum number of added entries that can be added, and a potential DoS if some entries contain a large amount of annotation data.

4MB should be plenty. A certificate+payload+signature annotations combo for rsa248 is around 1.5KB so room for 2700 signatures. More for ECC. 

Not sure I got on what side DoS you mean.

Compared to other options where we already see validation times in minutes or direct performance loss over time from calling the tags list API, these upper bounds should be quite meaningless.

Above else, you can do sharding if you really need 3K signatures. If anything we should consider if we should protect the user for such cases. If there really are 3K signatures then the image author is intentionally trying to cause puller to hang while verifying them. I think for a practical case our implementation could consider trying to verify up to 10-15 and then give up.

> Some clients have a limit on the annotation size (I'm hearing 4KB in containerd for the combination of key and value)

We should define that. Annotations are only for small fields like signatures. When the user needs to store a big amount of data(SBOM etc) they should use a separate descriptor.

> We need some testing with existing runtimes to see how they handle nested Index's, and manifest entries in an Index without a platform included. Will runtimes descend down a manifest without a platform or will it try to run an SBOM without a platform defined?

If it helps, I have these 4 test images with different combinations https://gist.github.com/tonistiigi/ac02f9d1ef948f2ef482057c988e3beb


> It's not clear how to sign a single platform specific manifest that could exist in multiple manifests. Does there need to be a 3rd Index for just the platform specific manifest, located by a digest tag, separate from the multi-platform Index? And do clients need to query both the Index digest and the Image digest for tags listing extensions?

When you just say "sign a single platform specific manifest" what do you mean by that? You don't just sign a manifest, you create a signature object somewhere in the registry. Depending on where you want this signature to be found you decide where do you push it and if you modify an existing object or create a new one.

3rd Index should pretty much never be the solution. I don't see any valid cases for it.

If you want to end up with 2 signed multi-platform images that are different but share one common single arch manifest then you would sign both of the indexes. You will have 2 different multi-platform images with each of them having one signature.

If your goal is to find all signatures based on unsigned digest then you can modify the existing signed manifest or create a copy of it on a new tag using the proposed digest schema.

This proposal also does not constrain you that you can only add annotations to descriptors pointing to image index. You can create a descriptor to a single arch manifest, add annotations to it, and then use that descriptor inside multiple image indexes.

> If tags are immutable, it's not possible to update the digest tag to point to an extended image without creating deeply nested Indexes.

I don't understand what the "deeply nested indexes" have to do with immutable tags. If tags are immutable you can only set them once. If you would create another level of nested index(what I see no use for) you still need a tag where you push it. Afaics solution for this case is the hash (or counter) in the tagging scheme.

**Comment by sudo-bmitch** [comment]
@tonistiigi 
> > An Index has a maximum manifest size we need to remain below (4MB). There is a maximum number of added entries that can be added, and a potential DoS if some entries contain a large amount of annotation data.
> 
> 4MB should be plenty. A certificate+payload+signature annotations combo for rsa248 is around 1.5KB so room for 2700 signatures. More for ECC.

Today it would probably be fine, but descriptors are only going to grow in size as more annotations are used, and we consider transitions like sha512. That would happen at the same time people are adding more refers to an image. Perhaps the solution then would be increasing the size limit or supporting sharding, but both of those would be breaking changes for existing clients.

> Not sure I got on what side DoS you mean.

I can create an image today that is unsignable in this design. All that is needed is adding a descriptor to the index (either from another referrer, or from the original manifest descriptor) that includes a long list of annotations to reach the 4MB limit. Admittedly, this would be the user with write access to the repo pushing data that breaks their image. This could be from a bad library used by the author, a bad image author, or a bad image mirror. Once the bad data gets injected in one location, it's not clear how to delete it in a way that can be detected as a deletion upstream vs a desired local change that needs to be preserved/merged.

> Compared to other options where we already see validation times in minutes or direct performance loss over time from calling the tags list API, these upper bounds should be quite meaningless.

We should probably compare the end state rather than the intermediate state. If the intermediate state is this painful, that's more of a reason for registries to upgrade in the other proposals.

> Above else, you can do sharding if you really need 3K signatures. If anything we should consider if we should protect the user for such cases. If there really are 3K signatures then the image author is intentionally trying to cause puller to hang while verifying them. I think for a practical case our implementation could consider trying to verify up to 10-15 and then give up.

Ideally, the puller should only need to pull one manifest out of 3K by some kind of filtering support. This will likely result in more annotations to distinguish the descriptors from each other.

> > It's not clear how to sign a single platform specific manifest that could exist in multiple manifests. Does there need to be a 3rd Index for just the platform specific manifest, located by a digest tag, separate from the multi-platform Index? And do clients need to query both the Index digest and the Image digest for tags listing extensions?
> 
> When you just say "sign a single platform specific manifest" what do you mean by that? You don't just sign a manifest, you create a signature object somewhere in the registry. Depending on where you want this signature to be found you decide where do you push it and if you modify an existing object or create a new one.

If I try to deploy `docker.io/tonistiigi/test@sha256:f0f5829a16cf2a72ce9cfbaed4072897be253b1460983c51cc0fac842a9fa1d5`, how do I know if that image is signed, and how can I pull the SBOM for that image? If that same manifest happens to be included in multiple manifest lists, how do I know which of the manifest lists to pull to get this data? What happens if someone updates the content in the manifest list that I don't use?

> If you want to end up with 2 signed multi-platform images that are different but share one common single arch manifest then you would sign both of the indexes. You will have 2 different multi-platform images with each of them having one signature.

I worry that duplicating the data in multiple manifest lists / indexes is going to be error prone. If someone signs one, but not the other, they're going to be confused why the image shows as unsigned and is missing other referrers.

> If your goal is to find all signatures based on unsigned digest then you can modify the existing signed manifest or create a copy of it on a new tag using the proposed digest schema.

I think we're going to end up with an Index per manifest, and a digest schema tag for each manifest.

> > If tags are immutable, it's not possible to update the digest tag to point to an extended image without creating deeply nested Indexes.
> 
> I don't understand what the "deeply nested indexes" have to do with immutable tags. If tags are immutable you can only set them once. If you would create another level of nested index(what I see no use for) you still need a tag where you push it. Afaics solution for this case is the hash (or counter) in the tagging scheme.

Deeply nested indexes were suggested as a way to handle immutable tags on the previous meeting. Since you can't modify the existing image tag and digest schema tag, you could potentially add another index that extends the existing digest tag. That would trigger a recursive search that I don't think any of us like, so the best option may just be to say immutable tags cannot be extended once the digest schema tag is created.

**Comment by michaelb990** [comment]
Summarizing my thoughts on the issues with Proposal F here. I think some of these I brought up when we initially talked through this proposal and it looks like @sudo-bmitch has mentioned a couple as well. 

* Tag mutability: we've heard from a lot of bigger customers who explicitly do not want to allow tags to ever change because they want to guarantee that if they deploy `someapp:v1` today and need to scale their service tomorrow, the image won't have changed and they won't end up running heterogenous versions without their knowledge. 
* Digest tags / race conditions: Proposal F uses a similar idea that's been used other places of using tags to workaround the registry's lack of native support for reference artifact. However, this isn't what tags were designed to do and it requires us to push the complexity of handling concurrent updates and filtering onto clients. It also makes it harder to find images in a registry if there are hundreds / thousands of digest tags that you need to filter out.
* No support for filtering: I believe we've already identified at least 5 unique artifact types that people want to push to registries. I can think of signatures, SBoMs, and scan results off the top of my head, but I think there will be many more as this gains adoption. I think that it's a bit of a waste to make clients get the manifest list (or possibly list of lists) containing all references for an image when each client most likely only cares about a single type of artifact. 
* Inconsistent limit on references for an image: It seems like we're relying on the manifest size limit to stop the list of references from growing unbounded and avoid the need for pagination. That size limit is at least 4MB for all registries that I know about which should provide plenty of space for a reasonable number of references (thousands), but since these are just normal image indexes, it's possible we will see implementations start embedding data directly into those descriptors or wanting to add additional annotations to help clients identify the specific artifact they're using.

**Comment by dlorenc** [comment]
Great summary @michaelb990. I agree with all the points and can echo the requirements around tag immutability.

**Comment by chris-crone** [comment]
The starting point of Proposal F is: Can we use the existing image and distribution specifications to create a referencing model for metadata? The assumption being that making changes to the specifications would take time to propagate across the container ecosystem and users would run into issues because of that.

For the race on index update, I think there is general consensus that it should be solved even outside of the work this working group is doing. I could see an argument for filtering on things like annotations being useful for many applications outside of just this working group as well.

I haven't thought as much about immutable tags but that would be an issue that would need to be solved.

**Comment by jdolitsky** [comment]
Closing based on result of https://github.com/opencontainers/wg-reference-types/issues/56. Thanks all
