### ISSUE TITLE
[Vote] Should artifact type move out of annotations

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/wg-reference-types#64]
Voting seemed to work for picking a direction in this group, so here's a vote for #59. Should we move the annotation to be a first class type in artifact-spec and depend on the config media type in image-spec? Vote by giving a thumbs up to one of the two comments below. We'll leave this open for 1 week, and go with the community's decision on the 2022-07-19 meeting.

**Comment by sudo-bmitch** [comment]
Yes, get ride of the artifact type annotation and make it a dedicated field in artifact-spec, plus depend on the config media type in image-spec.

**Comment by sudo-bmitch** [comment]
No, use the annotation as described in proposal E today.

**Comment by jonjohnsonjr** [comment]
I'm uncomfortable voting on this without a definition of `artifactType` somewhere.

**Comment by sudo-bmitch** [comment]
> I'm uncomfortable voting on this without a definition of `artifactType` somewhere.

It would follow the same IANA usage we have with the config media type.

https://github.com/opencontainers/artifacts/blob/main/artifact-authors.md#defining-a-unique-artifact-type

My plan was to formally define that in a proposed spec of this is the direction we pick. Does that cover what you're looking for?

**Comment by jdolitsky** [comment]
My understanding is that a new `artifactType` field should be expected to have same format/validation `mediaType` as far as its type.

**Comment by SteveLasker** [comment]
`artifactType` is intended to represent an extensibility point.

It's the same behavior as defined in OCI Artifacts, where the Helm team can define their type, the SPDX SBOM team can define theirs, Joe Curly can define their type. OCI Artifacts used the `config.mediaType`. The new manifest raises `config.mediaType` to an `artifactType` property.

When we debated this in OCI Artifacts, rather than make OCI the clearing house for who owns the `mediaType`, we deferred to iana.org. 

Similar to operating system extensibility points, where someone can say the `.txt` format is associated with a "Text Document", there's an issue that captures localizable strings and icons: https://github.com/opencontainers/artifacts/issues/45.
This way, OCI isn't the clearing house/moderator. And registries can choose to support different `artifactTypes` with localized strings/icons

![image](https://user-images.githubusercontent.com/7647382/178623369-be565c1b-25fc-41e0-abfd-a62481ae1a41.png)

**Comment by jdolitsky** [comment]
We've decided to go with the first option for now:

> Yes, get rid of the artifact type annotation and make it a dedicated field in artifact-spec, plus depend on the config media type in image-spec.

**Comment by sudo-bmitch** [comment]
@silvin-lubecki @chris-crone A concern raced in the meeting is that #59 removes support for Docker Hub. Are there plans for Hub to support arbitrary config descriptor media types?

**Comment by sudo-bmitch** [comment]
[Docker says they'll have support for OCI Artifacts in Hub soon](https://github.com/docker/roadmap/issues/135), so I'm retracting my No vote.

**Comment by sudo-bmitch** [comment]
From today's meeting, we've moved forward with #59
