### ISSUE TITLE
[Vote] Partition digest tags by type

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/wg-reference-types#72]
In follow up to https://github.com/opencontainers/wg-reference-types/issues/65

**Comment by imjasonh** [comment]
Vote with 👍  for:

Digest tags should be partitioned by type, e.g.:

```
:sha256-abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.sbom (for SBOMs)
:sha256-abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.att (for attestations)
:sha256-abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.sig (for signatures)
:sha256-abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.cats (for cat pictures)
```

Upsides:
- clients who want to discover signatures for an image can do so by querying only `:sha256-abcd.sig`

Downsides:
- clients who want to collect all attachments for a manifest have to either list and match for `:sha256-abcd.*`
  - or maintain an allowlist of types they know they care about (`.sbom`, `.att`, `.sig`) and potentially miss out on other types (`.cats`)
- the strings `.sbom`, etc., have meaning, and adding a new one means communicating what `.cats` means to clients.

**Comment by imjasonh** [comment]
Vote for 👍  for:

Digest tags should not be partitioned; all attachments should be discovered from a single tag:

```
:sha256-abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd
```

This one tag would point to a single manifest including attachments of all types.

Upsides:
- clients who want to collect all attachments for a manifest only have to make one query

Downsides:
- clients who want to discover only signatures for an image must filter the manifest returned by `:sha256-abcd`, which may include lots of things they don't care about
- more updates to the same manifest tag leads to increased likelihood of a racy update and data loss
  - this isn't 100% mitigated by partitioning, it's just theoretically less likely to happen
- manifests are more likely to grow larger since they contain manifest descriptors for signatures, attestations, cat pictures, etc. -- we're theoretically more likely to hit the 4MB limit recommended by distribution-spec

**Comment by sudo-bmitch** [comment]
A big upside to the single tag is the returned index exactly matches the API response, resulting in a lot more consistency in client code that needs to support both the tag or the API.

> clients who want to discover only signatures for an image must filter the manifest returned by :sha256-abcd, which may include lots of things they don't care about

This still exists with the API response since server-side filtering support, if it's added, is not required. So clients must have code to filter the responses for their needed type regardless of the option we pick here.

> manifests are more likely to grow larger since they contain manifest descriptors for signatures, attestations, cat pictures, etc. -- we're theoretically more likely to hit the 4MB limit recommended by distribution-spec

By the time we get to this point, I'd hope that either 1) we increase the manifest size limit, or 2) the API is supported on the registry. However, paging is not supported in the predictable tag method, so this is a downside of that change and sharding the tags only delays the issue. It's not something I'm particularly concerned about with well behaved clients since a descriptor is only a couple hundred bytes, so taking a bad case of 500 bytes per descriptor on average, that's still roughly 8,000 artifacts for a single manifest.

When thinking of how to write the client library code to support both the API response and predictable tags for generic clients, the type extensions add a lot of overhead. The library needs to include client side filtering for the API, and then translate that filtering to a type extension, and the fall back is to listing all tags and pulling all matching manifests.

**Comment by imjasonh** [comment]
Thanks @sudo-bmitch, I think your arguments are swaying me. In particular, the idea that a client would get the same response from the references endpoint and the manifest tagged `:sha256-abcd` seems really nice.

I agree the manifest size limit is probably not a huge concern ("[4 MB] ought to be enough for anybody" 😆) at least for the immediate future, and the solution in any case is either to increase the limit, or to have actual references support.

I'm changing my vote. 👍

**Comment by sudo-bmitch** [comment]
From today's meeting, we've decided to go with a single predictable tag.
